name = "boiltask-oj-worker"
main = "src/index.ts"
compatibility_date = "2024-04-09"
compatibility_flags = ["nodejs_compat_v2"]
[observability]
enabled = true
[assets]
directory = "./assets"
binding = "ASSETS"
